theme: jekyll-theme-hacker
title: dnscrypt-proxy-pihole
description: Preconfigured deb package for every Raspberry Pi and Pi-hole to use only best DNSCrypt, DNS-over-HTTPS and No-Log servers
show_downloads: false
